### ISSUE TITLE
Consider splitting index.ts into multiple files?

### ISSUE THREAD

**Issue by jcbhmr** [isaacs/node-primordials#4]
If index.ts were to be split into multiple files, this would greatly add manual tree-shaking for CJS users https://web.dev/commonjs-larger-bundles/ and also assist in splitting the massive file into component parts.

Before I found this existing project today, I had made some progress towards my own `@jcbhmr/node-primordials` npm package: https://github.com/jcbhmr/node-primordials/tree/esm/src where I tried to split things into class-based or namespace-based files. Plus a util.ts for all the helper things, but that could be split down even farther if needed.

**Comment by isaacs** [comment]
Sure, patch welcome.

**Comment by jcbhmr** [comment]
I went ahead with my own package and made it into this: https://github.com/nodefill/primordials -- it goes into a bit of a different direction than I originally described 👆 in the Issue above since it exposes **every single thing** as an individual file as opposed to grouped files. I could make it so that each `Array.js` file also exported `ArrayPrototypePush` etc stuff too... 🤷‍♂️ lmk what you think

Pros to this:
- It's very easy to MANUALLY tree-shake your code (i.e. only import what you need vs barrel import)
- You can autogenerate _only half_ the project (since it's in separate files) instead of all or none.

Cons to this:
- You essentially NEED to autogenerate the code files. 760 in src/ is too much 🤯
- A lot of files. 760 is a lot of files.

Some other differences of https://github.com/nodefill/primordials:
- DOES NOT have process-related stuff #6 
- DOES have *Constructor items
- DOES have the makeSafe() and SafeClass things
- DOES NOT ship an ESM build; instead relying on CJS=>ESM binding support
- DOES have all the SafePromise* stuff

I'd love to somehow merge these two projects together since I think they are both trying to accomplish the same thing.

<sup>I've invited you as a Collaborator thingie on GitHub. You don't have to accept; my feelings won't be hurt ❤️</sup>
