### ISSUE TITLE
Fails to import in browsers

### ISSUE THREAD

**Issue by jcbhmr** [isaacs/node-primordials#5]
![image](https://github.com/isaacs/node-primordials/assets/61068799/34cec216-5fb9-48f4-86ad-cb2a93844df3)

Try this in your devtools
```js
let m1; m1 = await import("https://esm.sh/node-primordials")
let m2; m2 = await import("https://esm.run/node-primordials")
let m3; m3 = await import("https://unpkg.com/node-primordials")
```

**Comment by isaacs** [comment]
It's a hybrid module.  If you're loading from an ESM env, you need to specify that you want the "module", not the "main".  For example: https://unpkg.com/node-primordials?module

**Comment by jcbhmr** [comment]
Doesn't work.

![image](https://github.com/isaacs/node-primordials/assets/61068799/8e1280e5-077c-44ea-a895-427d57291ff8)

It's probably down to the use of `process` without a `if (typeof process !== "undefined")` gate? 🤔

**Comment by isaacs** [comment]
What browser are you using? It loads fine in Safari.

**Comment by isaacs** [comment]
Ah, I see it. Just need a better fallback.
